app/menu/__init__.py
from flask import Blueprint


menu_blueprint = Blueprint('menu', __name__)

from . import views

app/menu/views.py
from flask import render_template
from app.models import MenuItem
from . import menu_blueprint as menu

@menu.route('/menu')
def list_menuitems():
    """
    List all departments
    """
    menu_items = MenuItem.query.all()
    return render_template('menu/menu_item_list.html',
                           object_list=menu_items, title="Menu")


@menu.route('/menu/<pid>')
def menuItemDetail(pid):
    """
    List all departments
    """
    menu_item = MenuItem.query.filter_by(id=pid).first()
    return render_template('menu/menu_item_detail.html',
                           food=menu_item, title="Menu item")

app/templates/menu/menu_item_detail.html
<!-- app/templates/menu/menu_item_detail.html -->

{% extends "base.html" %}
{% block title %}{{ food.name }}{% endblock %}
{% block body %}
    <div id="main" class="clear-top">
        <div class="container">
		<a href="/addToCart?productId={{request.args.get('productId')}}">Add to Cart</a>

<div class="row">
    <div class="col-12 my-5">
      <h1>{{ food.name }}</h1>
      <hr/>
    </div>
    <div class="col-12 col-md-6">
        <img class="img-fluid" src="{{ url_for('static', filename='img/product/'+food.image) }}">
    </div>
    <div class="col-12 col-md-6">
      {{ food.desc|nl2br }}<br/>
      <h4>Price: <strong>$ {{ food.price }}</strong></h4>
    <span class="submit-span">
            <a class="btn btn-info" href="{{ url_for('cart.addToCart')}}?itemId={{ food.id }}" role="button"><i class="fas fa-cart-plus" aria-hidden="true"></i> <i class="fas fa-long-arrow-alt-down" aria-hidden="true"></i></a>
	</span>    </div>
  </div>
        </div>
    </div>
{% endblock %}

app/templates/menu/menu_item_list.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Menu{% endblock %}
{% block body %}

<div class="row">
		<div class="col-12 mt-3">
			<h1>Featured Food</h1>
			<hr/>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<form method="get" action="" class="form-group form-inline sort-form">
				 <h5 class="ml-auto mr-3 mt-2">Sort By:</h5>
					<button type="submit" class="mr-1 form-control sort-btn {% if active_button == '-featured' %}sort-select{% endif %}" value="-featured" name="orderby">Featured First</button>
					<button type="submit" class="mr-1 form-control sort-btn {% if active_button == 'price' %}sort-select{% endif %}" value="price" name="orderby">Price: Low to High</button>
					<button type="submit" class="mr-1 form-control sort-btn {% if active_button == '-price' %}sort-select{% endif %}" value="-price" name="orderby">Price: High to Low</button>
			</form>
		</div>
	</div>
	<div class="row">
		{% for obj in object_list %}
			<div class="col my-3">
			<div class="card" style="width: 14rem;">
{#  {% if obj.image %}#}
    <a href="{{ url_for('menu.menuItemDetail', pid=obj.id) }}"><img class="card-img-top" src="{{ url_for('static', filename='img/product/'+obj.image) }}" alt="{{ obj.name }} logo" style="width: 14rem; height: 14rem;"></a>
{#  {% endif %}#}
  <div class="card-block mx-2 my-3">
    <p class="card-title text-center" style="font-size: 18px;"><a href="{{ url_for('menu.menuItemDetail', pid=obj.id) }}">{{ obj.name|truncate(20) }}</a></p>
    <!-- <p class="card-text">{{ obj.desc|truncate(150) }}</p> -->
    <p class="card-text" style="font-size: 18px;"><strong>$ {{ obj.price }}</strong></p>
<div class="text-center">
	<span class="submit-span">
            <a class="btn btn-info" href="{{ url_for('cart.addToCart')}}?itemId={{ obj.id }}" role="button"><i class="fas fa-cart-plus" aria-hidden="true"></i> <i class="fas fa-long-arrow-alt-down" aria-hidden="true"></i></a>
	</span>
    </div>
  </div>
</div>
			<!-- Add horizontal line after every row -->
			<!-- {% if loop.index is divisibleby 3 %}
			      </div></div><div class="row"><div class="col-12"><hr/>
			{% endif %} -->
		</div>
		{% endfor %}
	</div>
{% endblock %}