app/reservation/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, TimeField, TextAreaField, DateTimeField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired

from ..models import Reservation


class ReservationForm(FlaskForm):
    """
    Form for customers to create reservations
    """
    num_of_customers = StringField('Number of People', validators=[DataRequired()])
    reservation_dateTime = DateTimeField(id='res_datetime', format=('%d/%m/%Y %H:%M:%S'))
    special_desc = TextAreaField('Sepcial description')
    submit = SubmitField('Submit')

app/reservation/__init__.py
from flask import Blueprint


reservation_blueprint = Blueprint('reservation', __name__)

from . import views

app/reservation/views.py
from flask import url_for, abort, render_template, redirect, flash, request, session
from flask_login import login_required, current_user
from app.models import Reservation, User
from . import reservation_blueprint as reservation
from forms import ReservationForm
from app import db
from sqlalchemy import and_, or_, not_
from flask_wtf import Form
from wtforms.fields import DateField, DateTimeField

@reservation.route('/reservations')
@login_required
def view_reservations():
    """
    list all reservation order by created time (desc)
    """
    user_id = current_user.id
    userobj = User.query.filter_by(id=user_id).first()

    all_reservations = Reservation.query.filter_by(user_id=current_user.id).order_by(Reservation.created_on.desc()).all()

    return render_template('reservation/reservations.html', userobj=userobj,
                           reservation_list=all_reservations, title="Reservation List")


@reservation.route('/reservation/confirm')
@login_required
def confirm_reservation():
    """
    confirmation of reservation information for customers
    """
    user_id = current_user.id
    # reservation_id = session['rid']
    r_obj = Reservation.query.filter(Reservation.user_id == user_id).order_by(Reservation.created_on.desc()).first()
    # query = db.session().query(Reservation, User)
    # query = query.join(User, Reservation.user_id == User.id)\
    #     .filter(and_(Reservation.user_id == user_id, Reservation.status == 0)).all()
    # userobj = query[0].User
    userobj = User.query.filter_by(id=user_id).first()

    return render_template('reservation/reservation_confirm.html',
                           reservation_obj=r_obj, userobj=userobj, title="Reservation")


@reservation.route('/reservation', methods=['GET', 'POST'])
@login_required
def make_reservation():
    """
    make a reservation
    """
    user_id = current_user.id
    form = ReservationForm()
    rid=None
    if form.validate_on_submit():
        res_datetime=None
        reservation_obj = Reservation(user_id=user_id,
                                      num_of_customer=form.num_of_customers.data,
                                      res_datetime=form.reservation_dateTime.data.strftime('%Y-%m-%d %H:%M'),
                                      special_desc=form.special_desc.data)

        try:
            # add reservation_obj to the database, default status = 0; 1 for created (confirmed by user)
            db.session.add(reservation_obj)
            db.session.commit()
            # r = Reservation.query.filter(and_(Reservation.user == user_id,
            #                                   Reservation.res_datetime == res_datetime)).first()
            # rid=r.id
            flash('You have submitted a reservation request.')
        except:
            #
            flash('Error: unknown!')
        session['rid']=rid
        # redirect to reservation confirmation page
        return redirect(url_for('reservation.confirm_reservation'))

    # load reservation template
    return render_template('reservation/reservation.html',
                           form=form,
                           title="Make a Reservation")



# datetimepicker
class MyForm(Form):
    date = DateField(id='datepick')

@reservation.route('/res')
def index():
    form = MyForm()
    return render_template('reservation/res.html', form=form)


class DateForm(Form):
    dt = DateField('Pick a Date', format="%m/%d/%Y")

@reservation.route('/dform', methods=['post','get'])
def home():
    form = DateForm()
    if form.validate_on_submit():
        return form.dt.data.strftime('%x')
    return render_template('reservation/vort.html', form=form)


        # pub_time = request.form.get('publish_time')
        # update_time = request.form.get('update_time')
        #
        # if pub_time:
        #     post.pub_time = datetime.datetime.strptime(pub_time, "%Y-%m-%d %H:%M:%S")
        #
        # if update_time:
        #     post.update_time = datetime.datetime.strptime(update_time, "%Y-%m-%d %H:%M:%S")




class DateTimeForm(Form):
    DateTime = DateTimeField(id='res_datetime')

@reservation.route('/dtform', methods=['post','get'])
def dthome():
    form = DateTimeForm()
    # if form.validate_on_submit():
    #     return form.dt.data.strftime('%Y-%m-%d %H:%M:%S')
    return render_template('reservation/res_test.html', form=form)

app/templates/reservation/dt.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}This is an example page{% endblock %}

{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Hello, Bootstrap</h1>
    <div class="row">
      <div class='col-sm-6'>
        {{ wtf.quick_form(form) }}
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript">
    $(function () {
      $('#res_datetime').datetimepicker({format:'YYYY-MM-DD HH:mm:ss'});
    });
  </script>
{% endblock %}

app/templates/reservation/res.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}This is an example page{% endblock %}

{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Hello, Bootstrap</h1>
    <div class="row">
      <div class='col-sm-6'>
        {{ wtf.quick_form(form) }}
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript">
    $(function () {
      $('#datepick').datetimepicker();
    });
  </script>
{% endblock %}

app/templates/reservation/res_test.html
{% import "bootstrap/wtf.html" as wtf %}
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename="css/bootstrap-datetimepicker.min.css") }}">

<script src="{{ url_for('static', filename="js/bootstrap-datetimepicker.min.js") }}"></script>

<script>
    $(function () {
  $('#res_datetime').datetimepicker();
    });
     $(function () {
  $('#example').datetimepicker();
    });
</script>
</head>
<body>



{% block content %}
  <div class="container">
    <h1>Hello, Bootstrap</h1>
{#      <input type="text" class="form-control" id="example">#}
    <div class="row">
      <div class='col-sm-6'>
        {{ wtf.quick_form(form) }}
      </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

app/templates/reservation/reservation.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{#{% extends "bootstrap/base.html" %}#}
{% block title %}Fresh Food|{{ title }}{% endblock %}
{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename="css/bootstrap-datetimepicker.min.css") }}">

<script src="{{ url_for('static', filename="js/bootstrap-datetimepicker.min.js") }}"></script>
<script>
    $(function () {
  $('#res_datetime').datetimepicker({
        format: 'DD/MM/YYYY HH:mm:ss',
      });
    });
</script>
{% endblock %}
{% block body %}
{#<h1 class="mt-3">Reservation</h1>#}
  <div class="row">
	<div class="col-12 col-md-6 mx-auto my-3">
		<h1 class="text-center">Reservation</h1>
	</div>
</div>
{#<hr/>#}

<div class="content-section">
  {{ utils.flashed_messages() }}
</div>

{#  <div class="container">#}
{#    <h1>Hello, Bootstrap</h1>#}
{#      <input type="text" class="form-control" id="example">#}
{#    <div class="row">#}
{#      <div class='col-sm-6'>#}
{#        {{ wtf.quick_form(form) }}#}
{#      </div>#}
{#    </div>#}
{#  </div>#}

{#  <div class="row">#}
{#	<div class="col-12 col-md-6 mx-auto my-3">#}
{#		<h1 class="text-center">Reservation</h1>#}
{#	</div>#}
{#</div>#}
{#<hr/>#}
<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<form class="login-form" method="POST" data-endpoint="{{ url_for('reservation.make_reservation') }}">
  		{{ wtf.quick_form(form) }}
		</form>
	</div>
</div>

{% endblock %}

app/templates/reservation/reservation_confirm.html
{% extends "base.html" %}
{% block title %}Fresh Food|Table Reservation{% endblock %}
{% block body %}

<div class="container">
  <h2>Table Reservation Information</h2>
    <p>please confirm the information and then submit the reservation request</p>
  <table class="table">
    <tbody>
      <tr>
        <td>First Name</td>
        <td>{{ userobj.first_name }}</td>
      </tr>
      <tr>
        <td>Last Name</td>
        <td>{{ userobj.last_name }}</td>
      </tr>
       <tr>
        <td>Contact Phone</td>
        <td>{{ userobj.phone }}</td>
      </tr>
      <tr>
        <td>Email</td>
        <td>{{ userobj.email }}</td>
      </tr>
      <tr>
        <td>Number of Customers</td>
        <td>{{ reservation_obj.num_of_customer }}</td>
      </tr>
      <tr>
        <td>Special description</td>
        <td>{{ reservation_obj.special_desc }}</td>
      </tr>
    </tbody>
  </table>
    <div class="container">
  <div class="row">
    <div class="col-12 text-center"><a href="{{ url_for('reservation.view_reservations') }}"  class="btn btn-lg btn-success">confirm</a>

    </div>
  </div>
</div>
</div>
{% endblock %}

app/templates/reservation/reservations.html
{% extends "base.html" %}
{% block title %}Fresh Food|{{ title }}{% endblock %}
{% block body %}

<div class="container">
  <h2>your reservations</h2>
  <table class="table">
    <tbody>
    <tr>
        <td>No.</td>
        <td>Number of People</td>
        <td>assigned table</td>
        <td>reservation time</td>
        <td>reservation status</td>
        <td>created time</td>
    </tr>
    {% for res in reservation_list %}
    <tr>
        <td>{{ loop.index }}</td>
        <td>{{ res.num_of_customer }}</td>
        <td>{{ res.assigned_table_id }}</td>
        <td>{{ res.res_datetime }}</td>
        <td>{{ res.status }}</td>
        <td>{{ res.created_on }}</td>

    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/reservation/vort.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>DatePicker Example</title>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script>
	$(function() {
		$( ".dtpick" ).datepicker();
	});
	</script>
</head>
<body>


<form method="post" action="">
    {{ form.hidden_tag() }}
    {{ form.dt(class="dtpick") }}
    <button type="submit">Go</button>
</form>


</body>
</html>